import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  modalContent: {
    width: '94%',
    paddingVertical: 16,
    paddingBottom: 28,
    paddingHorizontal: 16,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
    // gap: 5,
    display: 'flex',
    // flexWrap: 'wrap',
    justifyContent: 'space-around',
    position: 'relative',
    minHeight: 430,
  },
  modalTitle: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitleText: {
    fontSize: 23,
    color: '#3d3d3d',
    fontFamily: 'Pretendard-Bold',
  },
  modalIcon: {},
  searchBox: {
    height: '500%',
    top: '110%',
    width: '100%',
    position: 'absolute',
    backgroundColor: 'white',
    zIndex: 3,
  },
  addMenu: {flexDirection: 'row'},
  addMenuContainer: {
    backgroundColor: '#EAF0FF',
    width: '44%',
    margin: 10,
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  addMenuImage: {width: 100, height: 100},
  addMenuContainerText: {
    fontSize: 16,
    color: '#3d3d3d',
    fontFamily: 'Pretendard-Bold',
  },
  loadingText: {
    fontFamily: 'Pretendard-Light',
    fontSize: 14,
    color: '#3d3d3d',
  },
  bookmarkContainer: {
    margin: 4,
    // padding: 12,
    // paddingTop: 20,
    borderRadius: 10,
    backgroundColor: '#F3F4F7',
    maxHeight: 200,
    width: '100%',
  },
  bookmarkTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 10,
  },
  bookmarkTitle: {
    color: '#3d3d3d',
    fontSize: 18,
    fontFamily: 'Pretendard-Bold',
    // marginBottom: 2,
    paddingHorizontal: 16,
  },
});
