import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  body: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    paddingBottom: 80,
  },
  topContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    backgroundColor: 'white',
    height: 60,
  },
  topText: {
    fontSize: 16,
    fontFamily: 'Pretendard-Bold',
    color: '#3d3d3d',
  },
  topIcon: {position: 'absolute', left: 20},
  bodyContainer: {
    padding: 20,
  },
  alertContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
  },
  alertTextConatiner: {
    display: 'flex',
  },
  alertText: {
    paddingStart: 10,
    paddingBottom: 2,
    fontFamily: 'Pretendard-Regular',
    fontSize: 15,
    letterSpacing: -0.3,
    color: 'black',
  },
  alertTimeText: {
    paddingStart: 11,
    fontFamily: 'Pretendard-Light',
    fontSize: 13,
    letterSpacing: -0.3,
    color: 'black',
    opacity: 0.5,
  },
  noNotificationText: {
    paddingStart: 10,
    paddingBottom: 2,
    fontFamily: 'Pretendard-Regular',
    fontSize: 15,
    letterSpacing: -0.3,
    color: 'black',
  },
  alertTextChecked: {
    paddingStart: 10,
    paddingBottom: 2,
    fontFamily: 'Pretendard-Regular',
    fontSize: 15,
    letterSpacing: -0.3,
    color: '#5E6066',
  },
  alarmTitleBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 4,
    width: '100%',
  },
  alarmWhiteBox: {
    width: '88%',
    backgroundColor: 'white',
    borderRadius: 10,
    elevation: 2,
    padding: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  titleBoxText: {
    fontSize: 16,
    color: '#3d3d3d',
    fontFamily: 'Pretendard-SemiBold',
  },
  actionButton: {
    margin: 4,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '46%',
    borderRadius: 10,
  },
  isRecord: {backgroundColor: '#DB8989'},
  later: {backgroundColor: '#EBC5C5'},
  actionText: {
    fontSize: 12,
    color: 'white',
    fontFamily: 'Pretendard-Bold',
  },
  editMartAmountForm: {width: '88%'},
  background: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
